marks=[95,89,85,99,100]
print(marks)
print(marks[0])
print(marks[1])
print(marks[2])
print("Reverse comdition with Minus (-) It will be start from the last of the marks")
print(marks[-1])
print(marks[-2])
print(marks[-3])
marks.append(90)
print("at one time morethan two marks will be printed")
print(marks[0:6])
print("pinting of marks with the help of for loop")
for score in marks:
    print(score)
print("Addint of marks ")
marks.append(94)
print(marks)
print("inserting of marks by its position")
marks.insert(0,91)
marks.insert(4,70)
print(marks)
print("checking of marks ")
print(90 in marks)
print(91 in marks)
print(93 in marks)
print("checking how many marks is there")
print(len(marks))
print("printing of marks by using while loop")
i = 0
while i<len(marks):
    print(marks[i])
    i=i+1
print("for clearing the marks")
marks.clear()
print(marks)